name: Pottery submission
description: Upload a pottery image and fill in details. A bot will add it to the gallery.
title: "New piece: <identifier>"
labels: [submission]
body:
  - type: input
    id: identifier
    attributes:
      label: Personal identifier
      description: e.g., BQ‑042 or any label you use.
      placeholder: BQ-042
    validations:
      required: true
  - type: input
    id: glaze
    attributes:
      label: Glaze
      placeholder: e.g., Shino, Celadon, Ash, Tenmoku
  - type: input
    id: clay
    attributes:
      label: Clay body
      placeholder: e.g., Porcelain, Stoneware, Earthenware
  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: Optional details about firing schedule, reduction/oxidation, etc.
  - type: input
    id: tags
    attributes:
      label: Tags (comma‑separated)
      placeholder: cup, bowl, vase
  - type: attachments
    id: images
    attributes:
      label: Image(s)
      description: Upload at least one clear photo. First will be featured.
    validations:
      required: true
